### ISSUE TITLE
bevy 0.10 support 

### ISSUE THREAD

**Issue by kumorig** [bonsairobo/bevy_triplanar_splatting#1]
Hey! I find your project interesting, and I'd love to use it with bevy 0.10.

Currently, the first wall I run into when trying to run the render-example with bevy 0.10 is this:
```rs
.add_asset_loader(
    bevy_triplanar_splatting::basis_linear_loader::BasisLinearLoader {
                                           ^ the trait `AssetLoader` is not implemented for `BasisLinearLoader`
```

Of course, I have no idea of how big of an ask it is, but I'm crossing my fingers and hoping it's something simple.

**Comment by bonsairobo** [comment]
@kumorig Reason for closing? Upgrading to bevy 0.10 is a reasonable ask.

**Comment by bonsairobo** [comment]
Implemented here: https://github.com/bonsairobo/bevy_triplanar_splatting/commit/706f2fedd2186a8f88e22d8c05d62aec143674ea
